Fix clippy warnings&erros
gahag/bgrep pull request #2
Opened 2019-03-24 11:06 UTC by Aloxaf

This is a very simple PR: I ran clippy and corrected the code as it wants.

[Clippy](https://github.com/rust-lang/rust-clippy) is a good tool to improve your Rust code :D

2019-03-24 19:10 UTC, gahag commented
Thanks for taking your time into this! Clippy seems to be great, thanks for telling me about it. I believe it found one real bug in my code, and your PR solves it. I just have some minor reviews.

2019-03-24 19:14 UTC, gahag requested changes

2019-03-24 19:14 UTC, gahag commented on src/grep.rs
> +  pattern: &str,
This part is already adressed in #1 , so I'll have it from there. Can you revert this part please?

2019-03-24 19:14 UTC, gahag commented on src/grep.rs
> +    stdout.write_all(bs)?;
I believe this solves a bug. A call to `write` that doesn't output all bytes would be considered successful. Many thanks for finding this.

2019-03-25 03:02 UTC, Aloxaf commented
Thanks for your advice. I have reverted it by a new commit. Is this OK?

2019-03-25 06:49 UTC, gahag commented
This is perfect. Once again, many thanks for your contribution. I will merge this tomorrow as soon as I get on my pc.

2019-03-25 17:48 UTC, gahag approved these changes

2019-03-25 17:49 UTC, merged